#!/usr/bin/env bash

echo "------ HOOK START - BUILD -------"
printenv
if [[ "$BUILD_PATH" == *.cc ]];
	then
		DOCKERFILE="Dockerfile.cc"
  elif [[ "$BUILD_PATH" == *.deb  ]];
  then
    DOCKERFILE="Dockerfile.deb"
	else
		DOCKERFILE="Dockerfile"
fi

if [[ "$DOCKER_TAG" == *-beta* ]]; 
	then 
		echo "Building beta release, stripping BRANCH_NAME from arguments"; 
		docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$SOURCE_COMMIT -t $IMAGE_NAME -f $DOCKERFILE .;
	else 
		echo "Building stable release, using BRANCH_NAME from arguments"; 
		docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg BRANCH_NAME=$DOCKER_TAG --build-arg VCS_REF=$SOURCE_COMMIT -t $IMAGE_NAME -f $DOCKERFILE .;
fi

echo "------ HOOK END - BUILD -------"
